image: jasonbarrella/libdim:latest

build:
  stage: build
  script:
    - pwd
    - ./bootstrap
    - ./configure
    - make
    - make rpm
    - chmod -R 777 /root/rpmbuild/RPMS
    # - ls -lR /root/rpmbuild/RPMS
    # - cp -r /root/rpmbuild/RPMS /builds/jbarrell/libdim/
    # - chmod 777 /builds/jbarrell/libdim/libdim-devel-20.07-3.x86_64.rpm
    # - ls -l 
  artifacts:
    paths:
    # - '/root/rpmbuild/**''
    # - /root/rpmbuild/RPMS/x86_64/libdim-devel-20.07-3.x86_64.rpm
    - /root/rpmbuild/RPMS
      