image: jasonbarrella/libdim:latest


variables:
  EOS_PATH: ${EOS_PATH}/packages/centos6
  EOS_ACCOUNT_USERNAME: $EOS_USER
  EOS_ACCOUNT_PASSWORD: $EOS_PASS
  CI_OUTPUT_DIR: /builds/jbarrell/libdim/RPMS

  
build:
  stage: build
  only:
    - master
  script:
    - ./bootstrap
    - ./configure
    - make
    - make rpm
    - chmod -R 755 /root/rpmbuild/RPMS
    - cp -r /root/rpmbuild/RPMS /builds/jbarrell/libdim/
  artifacts:
    paths:
    - /builds/jbarrell/libdim/RPMS/**

deployment:
  # Executed during the deploy stage
  stage: deploy
  # Only when the master branch is pushed
  only:
    - master
  # Custom docker image providing the needed tools to deploy in EOS
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  script:
  # Script that performs the deploy to EOS. Makes use of the variables defined in the project
  # It will copy the generated content to the folder in EOS
  - deploy-eos
      