include: '/build-aux/ci-template.yml'


build_centos6:
  extends: .build_centos_yum
  before_script:
      - ./bootstrap
  variables:
    OS: centos6

build_centos7:
  extends: .build_centos_yum
  before_script:
      - ./bootstrap
  variables:
    OS: centos7

build_centos8:
  extends: .build_centos_dnf
  variables:
    REQUIRED_PACKAGES: motif-devel
    OS: centos8

deployment:
  stage: deploy
  only:
    - tags
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  script:
    - deploy-eos
