image: jasonbarrella/libdim:centos6


variables:
  EOS_PATH: ${RPM_EOS_PATH}/packages/centos6
  EOS_ACCOUNT_USERNAME: $EOS_SERV_USER
  EOS_ACCOUNT_PASSWORD: $EOS_SERV_PASS
  CI_OUTPUT_DIR: /builds/jbarrell/libdim/RPMS

  
build:
  stage: build
  only:
    - master
  script:
    - ./bootstrap
    - ./configure
    - make
    - make rpm
    - chmod -R 755 /root/rpmbuild/RPMS
    - cp -r /root/rpmbuild/RPMS /builds/jbarrell/libdim/
  artifacts:
    paths:
    - /builds/jbarrell/libdim/RPMS/**

deployment:
  stage: deploy
  only:
    - master
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  script:
  - deploy-eos
      