image: jasonbarrella/libdim:latest

build:
  stage: build
  script:
    - ./bootstrap
    - ./configure
    - make
    - make rpm
    - ls -lR /root/rpmbuild/RPMS
  artifacts:
    paths:
    # - '/root/rpmbuild/**''
    - /root/rpmbuild/RPMS/x86_64/libdim-devel-20.07-3.x86_64.rpm