.\"                                      Hey, EMACS: -*- nroff -*-
.\" $Id: dim-config.1,v 1.2 2004/12/15 23:49:07 cholm Exp $
.\" 
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH DIM-CONFIG 1 "January  4, 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
dim-config \- information on Dim installation
.SH SYNOPSIS
.B dim-config
.RI [ options ] 
.SH DESCRIPTION
\fBdim-config\fP gives information on \fBDim\fR
installation. 
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-\-help
Show summary of options.
.TP
.B \-\-version
Show version of \fBThread\-\-\fR.
.TP
.B \-\-prefix
Gives the installation prefix.
.TP
.B \-\-libdir
Gives path to libraries.
.TP
.B \-\-includedir
Gives path to headers. 
.TP
.B \-\-libs
Gives linkage information.
.TP
.B \-\-cppflags
Gives preprocessor information.
.SH SEE ALSO
\fBDIM\fR is fully documented at 
.US http://cern.ch/dim
.B http://cern.ch/dim
.UE
.SH AUTHOR
This manual page was written by Christian Holm <cholm@nbi.dk>,
for the Debian GNU/Linux system (but may be used by others).
.\" 
.\" EOF
.\" 

